package travelagency;

/**
 *
 * @author trian
 */
public class AccommodationForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AccommodationForm.class.getName());

    /**
     * Creates new form AccommodationForm
     */
    public AccommodationForm() {
        initComponents();
        loadData();
    }
    
    public void loadData() {                                         
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            // Define ALL 15 Columns
            model.setColumnIdentifiers(new Object[]{
                "ID", "Name", "Type", "Rating", "Stars", "Status", 
                "Street", "Num", "PostCode", "Dest ID", "Phone", 
                "Email", "Capacity", "Price", "Facilities"
            });

            try {
                java.sql.Connection con = DBConnection.connect();
                String sql = "SELECT * FROM accommodation"; 
                java.sql.PreparedStatement pst = con.prepareStatement(sql);
                java.sql.ResultSet rs = pst.executeQuery();

                while(rs.next()){
                    // Get all 15 columns from the database
                    String col1 = rs.getString("acc_id"); 
                    String col2 = rs.getString("acc_name"); 
                    String col3 = rs.getString("acc_type"); 
                    String col4 = rs.getString("acc_rating"); 
                    String col5 = rs.getString("acc_stars"); 
                    String col6 = rs.getString("acc_status"); 
                    String col7 = rs.getString("acc_street"); 
                    String col8 = rs.getString("acc_street_num"); 
                    String col9 = rs.getString("acc_postcode"); 
                    String col10 = rs.getString("acc_dst_id"); 
                    String col11 = rs.getString("acc_phone"); 
                    String col12 = rs.getString("acc_email"); 
                    String col13 = rs.getString("acc_roomcapacity"); 
                    String col14 = rs.getString("acc_pricepernight"); 
                    String col15 = rs.getString("acc_facilities");

                    // Add the row with all 15 values
                    model.addRow(new Object[]{
                        col1, col2, col3, col4, col5, col6, col7, 
                        col8, col9, col10, col11, col12, col13, col14, col15
                    });
                }
                con.close(); 
            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Add");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Update");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Delete");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addComponent(jButton1)
                .addGap(49, 49, 49)
                .addComponent(jButton2)
                .addGap(47, 47, 47)
                .addComponent(jButton3)
                .addContainerGap(359, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new AccommodationDialog(this, null).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
             javax.swing.JOptionPane.showMessageDialog(this, "Select a hotel to update.");
            return;
        }
        
        // Get ID from Column 0
        int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        
        // Open Dialog in EDIT mode (pass ID)
        new AccommodationDialog(this, id).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a hotel to delete.");
            return;
        }
        
        int id = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
        String name = jTable1.getValueAt(row, 1).toString();
        
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to delete '" + name + "'?", 
                "Delete Accommodation", 
                javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try (java.sql.Connection con = DBConnection.connect();
                 java.sql.PreparedStatement pst = con.prepareStatement("DELETE FROM accommodation WHERE acc_id=?")) {
                
                pst.setInt(1, id);
                pst.executeUpdate();
                
                javax.swing.JOptionPane.showMessageDialog(this, "Deleted Successfully!");
                loadData(); // Refresh table
                
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AccommodationForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
