package travelagency;
import java.sql.*;
import java.util.HashMap;

public class ManagesForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManagesForm.class.getName());
    private final HashMap<String, String> adminMap = new HashMap<>(); // Name -> AT
    private final HashMap<String, String> branchMap = new HashMap<>(); // City -> Code
    private String oldAdminAT = "";
    private String oldBranchCode = "";
    
    public ManagesForm() {
        initComponents();
        fillAdminCombo();
        fillBranchCombo();
        loadData();
    }
    
    private void fillAdminCombo() {
        cmbAdmin.removeAllItems();
        try (Connection con = DBConnection.connect();
             PreparedStatement pst = con.prepareStatement(
                 "SELECT a.adm_AT, w.wrk_name, w.wrk_lname FROM admin a JOIN worker w ON a.adm_AT = w.wrk_AT")) {
            
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String fullName = rs.getString("wrk_name") + " " + rs.getString("wrk_lname");
                String at = rs.getString("adm_AT");
                adminMap.put(fullName, at);
                cmbAdmin.addItem(fullName);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void fillBranchCombo() {
        cmbBranch.removeAllItems();
        try (Connection con = DBConnection.connect();
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery("SELECT br_code, br_city, br_street FROM branch")) {
            
            while (rs.next()) {
                String branchDisplay = rs.getString("br_city") + " (" + rs.getString("br_street") + ")";
                String code = rs.getString("br_code");
                branchMap.put(branchDisplay, code);
                cmbBranch.addItem(branchDisplay);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void loadData(){                                        
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new Object[]{"Admin AT", "Admin Name", "Branch City", "Branch Code"});

        try (Connection con = DBConnection.connect();
             PreparedStatement pst = con.prepareStatement(
                 "SELECT m.mng_adm_AT, w.wrk_name, w.wrk_lname, b.br_city, m.mng_br_code " +
                 "FROM manages m " +
                 "JOIN worker w ON m.mng_adm_AT = w.wrk_AT " +
                 "JOIN branch b ON m.mng_br_code = b.br_code")) {

            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("mng_adm_AT"),
                    rs.getString("wrk_name") + " " + rs.getString("wrk_lname"),
                    rs.getString("br_city"),
                    rs.getString("mng_br_code")
                });
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        cmbAdmin = new javax.swing.JComboBox<>();
        cmbBranch = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Branch Code");

        jLabel2.setText("Admin Code");

        jButton2.setText("Add");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton4.setText("Delete");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        cmbAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton3.setText("Update");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(40, 40, 40)
                                .addComponent(cmbAdmin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(38, 38, 38)
                                .addComponent(cmbBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(42, 42, 42)
                        .addComponent(jButton3)
                        .addGap(33, 33, 33)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String adminAT = adminMap.get((String) cmbAdmin.getSelectedItem());
        String branchCode = branchMap.get((String) cmbBranch.getSelectedItem());

        try (Connection con = DBConnection.connect();
             PreparedStatement pst = con.prepareStatement(
                 "INSERT INTO manages (mng_adm_AT, mng_br_code) VALUES (?, ?)")) {
            
            pst.setString(1, adminAT);
            pst.setString(2, branchCode);
            pst.executeUpdate();
            
            javax.swing.JOptionPane.showMessageDialog(this, "Management assignment added!");
            loadData();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error (Possible duplicate): " + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int row = jTable1.getSelectedRow();
        if (row != -1) {
            oldAdminAT = jTable1.getValueAt(row, 0).toString();
            oldBranchCode = jTable1.getValueAt(row, 3).toString();

            cmbAdmin.setSelectedItem(jTable1.getValueAt(row, 1).toString());

            String cityName = jTable1.getValueAt(row, 2).toString();
            for (int i = 0; i < cmbBranch.getItemCount(); i++) {
                if (cmbBranch.getItemAt(i).startsWith(cityName)) {
                    cmbBranch.setSelectedIndex(i);
                    break;
                }
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) return;

        String adminAT = jTable1.getValueAt(row, 0).toString();
        String branchCode = jTable1.getValueAt(row, 3).toString();

        try (Connection con = DBConnection.connect();
             PreparedStatement pst = con.prepareStatement(
                 "DELETE FROM manages WHERE mng_adm_AT=? AND mng_br_code=?")) {
            
            pst.setString(1, adminAT);
            pst.setString(2, branchCode);
            pst.executeUpdate();
            loadData();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (oldAdminAT.equals("") || oldBranchCode.equals("")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a record first!");
        return;
    }

    String newAdminAT = adminMap.get((String) cmbAdmin.getSelectedItem());
    String newBranchCode = branchMap.get((String) cmbBranch.getSelectedItem());

    String sql = "UPDATE manages SET mng_adm_AT = ?, mng_br_code = ? " +
                 "WHERE mng_adm_AT = ? AND mng_br_code = ?";

    try (Connection con = DBConnection.connect();
         PreparedStatement pst = con.prepareStatement(sql)) {
        
        pst.setString(1, newAdminAT);
        pst.setString(2, newBranchCode);
        pst.setString(3, oldAdminAT);
        pst.setString(4, oldBranchCode);
        
        pst.executeUpdate();
         javax.swing.JOptionPane.showMessageDialog(this, "Assignment updated!");
        loadData();
    } catch (Exception e) {
         javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> new ManagesForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbAdmin;
    private javax.swing.JComboBox<String> cmbBranch;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
