package travelagency;

import java.sql.*;
import java.util.HashMap;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class ReservationForm extends javax.swing.JFrame {

    private HashMap<String, Integer> tripMap = new HashMap<>();
    private HashMap<String, Integer> custMap = new HashMap<>();
    
    private int oldTripId = -1;
    private int oldSeatNum = -1;

    public ReservationForm() {
        initComponents();
        fillCombos();
        loadData();
    }

    private void fillCombos() {
        try (Connection con = DBConnection.connect(); Statement st = con.createStatement()) {
            // Γέμισμα Ταξιδιών (Trip)
            cmbTrip.removeAllItems();
            ResultSet rs1 = st.executeQuery("SELECT tr_id, tr_departure FROM trip");
            while (rs1.next()) {
                String label = "Trip #" + rs1.getInt("tr_id") + " (" + rs1.getTimestamp("tr_departure") + ")";
                tripMap.put(label, rs1.getInt("tr_id"));
                cmbTrip.addItem(label);
            }

            // Γέμισμα Πελατών (Customer)
            cmbCust.removeAllItems();
            ResultSet rs2 = st.executeQuery("SELECT cust_id, cust_name, cust_lname FROM customer");
            while (rs2.next()) {
                String label = rs2.getString("cust_name") + " " + rs2.getString("cust_lname");
                custMap.put(label, rs2.getInt("cust_id"));
                cmbCust.addItem(label);
            }
            
            // Γέμισμα Status (ENUM)
            cmbStatus.setModel(new DefaultComboBoxModel<>(new String[] { "PENDING", "CONFIRMED", "PAID", "CANCELLED" }));
        } catch (Exception e) { e.printStackTrace(); }
    }

    private void loadData() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new Object[]{"Trip ID", "Seat #", "Cust ID", "Status", "Cost"});
        
        try (Connection con = DBConnection.connect(); Statement st = con.createStatement(); 
             ResultSet rs = st.executeQuery("SELECT * FROM reservation")) {
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("res_tr_id"), rs.getInt("res_seatnum"),
                    rs.getInt("res_cust_id"), rs.getString("res_status"),
                    rs.getBigDecimal("res_total_cost")
                });
            }
        } catch (Exception e) { e.printStackTrace(); }
    }
    
    private void selectComboItemById(JComboBox combo, HashMap<String, Integer> map, int id) {
        for (String label : map.keySet()) {
            if (map.get(label) == id) {
                combo.setSelectedItem(label);
                return;
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtSeat = new javax.swing.JTextField();
        cmbCust = new javax.swing.JComboBox<>();
        cmbStatus = new javax.swing.JComboBox<>();
        cmbTrip = new javax.swing.JComboBox<>();
        txtCost = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Trip ID");

        jLabel2.setText("Seat Number");

        jLabel3.setText("Customer ID");

        jLabel4.setText("Total Cost");

        jLabel5.setText("Status");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Add");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Update");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Delete");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(74, 74, 74)
                                .addComponent(txtCost))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbStatus, 0, 190, Short.MAX_VALUE)
                                    .addComponent(cmbCust, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbTrip, 0, 190, Short.MAX_VALUE)
                                    .addComponent(txtSeat))))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(37, 37, 37)
                        .addComponent(jButton3)
                        .addGap(32, 32, 32)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbTrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(cmbCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton4)
                        .addComponent(jButton3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int tripId = tripMap.get(cmbTrip.getSelectedItem().toString());
        int seatNum = Integer.parseInt(txtSeat.getText());
        int custId = custMap.get(cmbCust.getSelectedItem().toString());

        try (Connection con = DBConnection.connect()) {
            PreparedStatement checkPst = con.prepareStatement("SELECT tr_maxseats FROM trip WHERE tr_id = ?");
            checkPst.setInt(1, tripId);
            ResultSet rs = checkPst.executeQuery();
            if (rs.next() && seatNum > rs.getInt("tr_maxseats")) {
                JOptionPane.showMessageDialog(this, "Αδύνατη κράτηση! Το ταξίδι έχει μόνο " + rs.getInt("tr_maxseats") + " θέσεις.");
                return;
            }

            String sql = "INSERT INTO reservation (res_tr_id, res_seatnum, res_cust_id, res_status, res_total_cost) VALUES (?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, tripId);
            pst.setInt(2, seatNum);
            pst.setInt(3, custId);
            pst.setString(4, cmbStatus.getSelectedItem().toString());
            pst.setDouble(5, Double.parseDouble(txtCost.getText()));
            
            pst.executeUpdate();
            loadData();
            JOptionPane.showMessageDialog(this, "Η κράτηση έγινε!");
        } catch (Exception e) { 
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Σφάλμα: Ίσως η θέση είναι πιασμένη."); }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (oldTripId == -1) return;
            String sql = "UPDATE reservation SET res_tr_id=?, res_seatnum=?, res_cust_id=?, res_status=?, res_total_cost=? WHERE res_tr_id=? AND res_seatnum=?";
            try (Connection con = DBConnection.connect(); PreparedStatement pst = con.prepareStatement(sql)) {
                pst.setInt(1, tripMap.get(cmbTrip.getSelectedItem().toString()));
                pst.setInt(2, Integer.parseInt(txtSeat.getText()));
                pst.setInt(3, custMap.get(cmbCust.getSelectedItem().toString()));
                pst.setString(4, cmbStatus.getSelectedItem().toString());
                pst.setDouble(5, Double.parseDouble(txtCost.getText()));
                pst.setInt(6, oldTripId);
                pst.setInt(7, oldSeatNum);

                pst.executeUpdate();
                loadData();
                JOptionPane.showMessageDialog(this, "Ενημερώθηκε!");
            } catch (Exception e) { JOptionPane.showMessageDialog(this, "Update Error: " + e.getMessage()); }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     if (oldTripId == -1) return;
        try (Connection con = DBConnection.connect(); 
             PreparedStatement pst = con.prepareStatement("DELETE FROM reservation WHERE res_tr_id=? AND res_seatnum=?")) {
            pst.setInt(1, oldTripId);
            pst.setInt(2, oldSeatNum);
            pst.executeUpdate();
            loadData();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Delete Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        if (row != -1) {
            oldTripId = (int) jTable1.getValueAt(row, 0);
            oldSeatNum = (int) jTable1.getValueAt(row, 1);
            
            txtSeat.setText(String.valueOf(oldSeatNum));
            txtCost.setText(jTable1.getValueAt(row, 4).toString());
            cmbStatus.setSelectedItem(jTable1.getValueAt(row, 3).toString());
            // Συγχρονισμός Combos για Trip/Customer
            selectComboItemById(cmbTrip, tripMap, oldTripId);
            selectComboItemById(cmbCust, custMap, (int) jTable1.getValueAt(row, 2));
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReservationForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCust;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JComboBox<String> cmbTrip;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtSeat;
    // End of variables declaration//GEN-END:variables
}
