package travelagency;
import java.sql.*;
import java.util.HashMap;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trian
 */
public class TravelToForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TravelToForm.class.getName());
    private HashMap<String, Integer> tripMap = new HashMap<>();
    private HashMap<String, Integer> destMap = new HashMap<>();
  
    private int oldTripId = -1;
    private int oldDestId = -1;
    
    public TravelToForm() {
        initComponents();
        fillCombos();
        loadData();
    }
    
    private void fillCombos() {
        try (Connection con = DBConnection.connect(); Statement st = con.createStatement()) {
            
            cmbTrip.removeAllItems();
            ResultSet rs1 = st.executeQuery("SELECT tr_id, tr_departure FROM trip");
            while (rs1.next()) {
                String label = "Trip #" + rs1.getInt("tr_id") + " (" + rs1.getTimestamp("tr_departure") + ")";
                tripMap.put(label, rs1.getInt("tr_id"));
                cmbTrip.addItem(label);
            }

            // Destinations
            cmbDest.removeAllItems();
            ResultSet rs2 = st.executeQuery("SELECT dst_id, dst_name FROM destination");
            while (rs2.next()) {
                String name = rs2.getString("dst_name");
                destMap.put(name, rs2.getInt("dst_id"));
                cmbDest.addItem(name);
            }
        } catch (Exception e) { e.printStackTrace(); }
    }
    
    private void loadData() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        model.setColumnIdentifiers(new Object[]{"Trip ID", "Dest. ID", "Arrival", "Departure", "Sequence"});
        
        String sql = "SELECT * FROM travel_to ORDER BY to_tr_id, to_sequence";
        
        try (Connection con = DBConnection.connect(); Statement st = con.createStatement(); ResultSet rs = st.executeQuery(sql)) {
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("to_tr_id"),
                    rs.getInt("to_dst_id"),
                    rs.getTimestamp("to_arrival"),
                    rs.getTimestamp("to_departure"),
                    rs.getInt("to_sequence")
                });
            }
        } catch (Exception e) { JOptionPane.showMessageDialog(this, "Load Error: " + e.getMessage()); }
    }
    
    private void selectComboItemById(JComboBox combo, HashMap<String, Integer> map, int id) {
        for (Object item : map.keySet()) {
            if (map.get(item.toString()) == id) {
                combo.setSelectedItem(item);
                return;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtArrival = new java.awt.TextField();
        jLabel5 = new javax.swing.JLabel();
        txtSeq = new java.awt.TextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtDeparture = new java.awt.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        cmbTrip = new javax.swing.JComboBox<>();
        cmbDest = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Destination ID");

        jLabel4.setText("Arrival");

        jLabel5.setText("Trip ID");

        txtSeq.addActionListener(this::txtSeqActionPerformed);

        jButton2.setText("Add");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel6.setText("Sequence");

        jButton3.setText("Update");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setText("Departure");

        jButton4.setText("Delete");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        cmbTrip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbDest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtDeparture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtArrival, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtSeq, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbDest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbTrip, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jButton4)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbTrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(txtArrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSeq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSeqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeqActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String sql = "INSERT INTO travel_to (to_tr_id, to_dst_id, to_arrival, to_departure, to_sequence) VALUES (?, ?, ?, ?, ?)";
        try (Connection con = DBConnection.connect(); PreparedStatement pst = con.prepareStatement(sql)) {
            pst.setInt(1, tripMap.get(cmbTrip.getSelectedItem().toString()));
            pst.setInt(2, destMap.get(cmbDest.getSelectedItem().toString()));
            pst.setString(3, txtArrival.getText()); 
            pst.setString(4, txtDeparture.getText());
            pst.setInt(5, Integer.parseInt(txtSeq.getText()));

            pst.executeUpdate();
            loadData();
            JOptionPane.showMessageDialog(this, "Η στάση προστέθηκε!");
        } catch (Exception e) { JOptionPane.showMessageDialog(this, "Insert Error: " + e.getMessage()); }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    if (oldTripId == -1) return;
        String sql = "UPDATE travel_to SET to_tr_id=?, to_dst_id=?, to_arrival=?, to_departure=?, to_sequence=? WHERE to_tr_id=? AND to_dst_id=?";
        try (Connection con = DBConnection.connect(); PreparedStatement pst = con.prepareStatement(sql)) {
            pst.setInt(1, tripMap.get(cmbTrip.getSelectedItem().toString()));
            pst.setInt(2, destMap.get(cmbDest.getSelectedItem().toString()));
            pst.setString(3, txtArrival.getText());
            pst.setString(4, txtDeparture.getText());
            pst.setInt(5, Integer.parseInt(txtSeq.getText()));
            pst.setInt(6, oldTripId);
            pst.setInt(7, oldDestId);

            pst.executeUpdate();
            loadData();
            JOptionPane.showMessageDialog(this, "Το δρομολόγιο ενημερώθηκε!");
        } catch (Exception e) { JOptionPane.showMessageDialog(this, "Update Error: " + e.getMessage()); }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        if (row != -1) {
            oldTripId = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
            oldDestId = Integer.parseInt(jTable1.getValueAt(row, 1).toString());
            
            // Επιλογή στα ComboBoxes βάσει των IDs
            selectComboItemById(cmbTrip, tripMap, oldTripId);
            selectComboItemById(cmbDest, destMap, oldDestId);
            
            txtArrival.setText(jTable1.getValueAt(row, 2).toString());
            txtDeparture.setText(jTable1.getValueAt(row, 3).toString());
            txtSeq.setText(jTable1.getValueAt(row, 4).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       if (oldTripId == -1) return;
        try (Connection con = DBConnection.connect(); 
             PreparedStatement pst = con.prepareStatement("DELETE FROM travel_to WHERE to_tr_id=? AND to_dst_id=?")) {
            pst.setInt(1, oldTripId);
            pst.setInt(2, oldDestId);
            pst.executeUpdate();
            loadData();
            JOptionPane.showMessageDialog(this, "Η στάση διαγράφηκε!");
        } catch (Exception e) { JOptionPane.showMessageDialog(this, "Delete Error: " + e.getMessage()); }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TravelToForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbDest;
    private javax.swing.JComboBox<String> cmbTrip;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.TextField txtArrival;
    private java.awt.TextField txtDeparture;
    private java.awt.TextField txtSeq;
    // End of variables declaration//GEN-END:variables
}
