package travelagency;
import java.sql.*;
import java.util.HashMap;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class TripAccommodation extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TripAccommodation.class.getName());
    
    private HashMap<String, Integer> tripMap = new HashMap<>();
    private HashMap<String, Integer> accMap = new HashMap<>();

    public TripAccommodation() {
        initComponents();
        fillCombos();
        loadData();
    }
    
    private void loadData() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new Object[]{"ID", "Trip ID", "Hotel ID", "Check-In", "Check-Out", "Rooms", "Cost"});

        String sql = "SELECT * FROM trip_accommodation ORDER BY ta_check_in DESC";
        try (Connection con = DBConnection.connect(); Statement st = con.createStatement(); ResultSet rs = st.executeQuery(sql)) {
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("ta_id"), rs.getInt("ta_trip_id"), rs.getInt("ta_acc_id"),
                    rs.getTimestamp("ta_check_in"), rs.getTimestamp("ta_check_out"),
                    rs.getInt("ta_rooms"), rs.getBigDecimal("ta_total_cost")
                });
            }
        } catch (Exception e) { JOptionPane.showMessageDialog(this, "Load Error: " + e.getMessage()); }
    }
    
    private void fillCombos() {
    try (Connection con = DBConnection.connect(); Statement st = con.createStatement()) {
        // Trips
        cmbTrip.removeAllItems();
        ResultSet rs1 = st.executeQuery("SELECT tr_id, tr_departure FROM trip");
        while (rs1.next()) {
            String label = "Trip #" + rs1.getInt("tr_id") + " (" + rs1.getTimestamp("tr_departure") + ")";
            tripMap.put(label, rs1.getInt("tr_id"));
            cmbTrip.addItem(label);
        }

        // Accommodations/Hotels
        cmbAcc.removeAllItems();
        ResultSet rs2 = st.executeQuery("SELECT acc_id, acc_name FROM accommodation");
        while (rs2.next()) {
            String name = rs2.getString("acc_name");
            accMap.put(name, rs2.getInt("acc_id"));
            cmbAcc.addItem(name);
        }
        } catch (Exception e) { e.printStackTrace(); }
    }
    
    private void selectComboItem(JComboBox combo, HashMap<String, Integer> map, int id) {
        for (String label : map.keySet()) {
            if (map.get(label) == id) {
                combo.setSelectedItem(label);
                break;
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCost = new java.awt.TextField();
        jButton4 = new javax.swing.JButton();
        txtCheckOut = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        txtID = new java.awt.TextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtCheckIn = new java.awt.TextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cmbTrip = new javax.swing.JComboBox<>();
        cmbAcc = new javax.swing.JComboBox<>();
        txtRooms = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton4.setText("Delete");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        txtCheckOut.addActionListener(this::txtCheckOutActionPerformed);

        jLabel3.setText("Trip ID");

        txtID.addActionListener(this::txtIDActionPerformed);

        jLabel4.setText("Accommodation ID");

        jButton2.setText("Add");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel2.setText("Check In");

        jButton3.setText("Update");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        txtCheckIn.addActionListener(this::txtCheckInActionPerformed);

        jLabel7.setText("Check Out");

        jLabel10.setText("Total Cost");

        jLabel9.setText("Rooms");

        jLabel5.setText("ID");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        txtRooms.addActionListener(this::txtRoomsActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbTrip, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtCost, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                                    .addComponent(txtCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtCheckOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtRooms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(cmbAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(53, 53, 53)
                        .addComponent(jButton2)
                        .addGap(30, 30, 30)
                        .addComponent(jButton3)
                        .addGap(39, 39, 39)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbTrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtRooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton4)
                        .addComponent(jButton3)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       if (txtID.getText().isEmpty()) return;
        try (Connection con = DBConnection.connect(); 
            PreparedStatement pst = con.prepareStatement("DELETE FROM trip_accommodation WHERE ta_id=?")) {
            pst.setInt(1, Integer.parseInt(txtID.getText()));
            pst.executeUpdate();
            loadData();
        } catch (Exception e) { JOptionPane.showMessageDialog(this, "Delete Error: " + e.getMessage()); }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckOutActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String sql = "INSERT INTO trip_accommodation (ta_trip_id, ta_acc_id, ta_check_in, ta_check_out, ta_rooms, ta_total_cost) VALUES (?,?,?,?,?,?)";
        try (Connection con = DBConnection.connect(); PreparedStatement pst = con.prepareStatement(sql)) {
        pst.setInt(1, tripMap.get(cmbTrip.getSelectedItem().toString()));
        pst.setInt(2, accMap.get(cmbAcc.getSelectedItem().toString()));
        pst.setString(3, txtCheckIn.getText()); // YYYY-MM-DD HH:MM:SS
        pst.setString(4, txtCheckOut.getText());
        pst.setInt(5, Integer.parseInt(txtRooms.getText()));
        pst.setDouble(6, Double.parseDouble(txtCost.getText()));

        pst.executeUpdate();
        loadData();
        JOptionPane.showMessageDialog(this, "Η διαμονή καταχωρήθηκε!");
    } catch (Exception e) { JOptionPane.showMessageDialog(this, "Insert Error: " + e.getMessage()); }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    if (txtID.getText().isEmpty()) return;
        String sql = "UPDATE trip_accommodation SET ta_trip_id=?, ta_acc_id=?, ta_check_in=?, ta_check_out=?, ta_rooms=?, ta_total_cost=? WHERE ta_id=?";
    try (Connection con = DBConnection.connect(); PreparedStatement pst = con.prepareStatement(sql)) {
        pst.setInt(1, tripMap.get(cmbTrip.getSelectedItem().toString()));
        pst.setInt(2, accMap.get(cmbAcc.getSelectedItem().toString()));
        pst.setString(3, txtCheckIn.getText());
        pst.setString(4, txtCheckOut.getText());
        pst.setInt(5, Integer.parseInt(txtRooms.getText()));
        pst.setDouble(6, Double.parseDouble(txtCost.getText()));
        pst.setInt(7, Integer.parseInt(txtID.getText()));

        pst.executeUpdate();
        loadData();
    } catch (Exception e) { JOptionPane.showMessageDialog(this, "Update Error: " + e.getMessage()); }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckInActionPerformed

    private void txtRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomsActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        if (row != -1) {
            txtID.setText(jTable1.getValueAt(row, 0).toString());
        
        selectComboItem(cmbTrip, tripMap, (int)jTable1.getValueAt(row, 1));
        selectComboItem(cmbAcc, accMap, (int)jTable1.getValueAt(row, 2));
        
        txtCheckIn.setText(jTable1.getValueAt(row, 3).toString());
        txtCheckOut.setText(jTable1.getValueAt(row, 4).toString());
        txtRooms.setText(jTable1.getValueAt(row, 5).toString());
        txtCost.setText(jTable1.getValueAt(row, 6).toString());
    }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TripAccommodation().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbAcc;
    private javax.swing.JComboBox<String> cmbTrip;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.TextField txtCheckIn;
    private java.awt.TextField txtCheckOut;
    private java.awt.TextField txtCost;
    private java.awt.TextField txtID;
    private java.awt.TextField txtRooms;
    // End of variables declaration//GEN-END:variables
}
