package travelagency;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class TripHistoryForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TripHistoryForm.class.getName());

    public TripHistoryForm() {
        initComponents();   

    }
    
    private void loadHistoryData(String sql) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new Object[]{
            "Hist. ID", "Trip ID", "Departure", "Return", "Destinations", "Participants", "Revenue"
        });

        try (Connection con = DBConnection.connect();
             Statement st = con.createStatement();
             ResultSet rs = st.executeQuery(sql)) {

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("th_id"),
                    rs.getInt("th_trip_id"),
                    rs.getTimestamp("th_departure"),
                    rs.getTimestamp("th_return"),
                    rs.getInt("th_destinations_count"),
                    rs.getInt("th_participants_count"),
                    rs.getBigDecimal("th_total_revenue")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading history: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDep = new javax.swing.JTextField();
        txtRet = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDestCount = new javax.swing.JTextField();
        txtPartCount = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTripID = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtRevenue = new javax.swing.JTextField();
        search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Date From");

        jLabel2.setText("Date To");

        txtDep.setText("\"xx-xx-xxxx\"");
        txtDep.addActionListener(this::txtDepActionPerformed);

        txtRet.setText("\"xx-xx-xxxx\"");
        txtRet.addActionListener(this::txtRetActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("Trip ID");

        jLabel4.setText("Destination Count");

        jLabel5.setText("Participation Count");

        txtDestCount.addActionListener(this::txtDestCountActionPerformed);

        txtPartCount.addActionListener(this::txtPartCountActionPerformed);

        txtID.setEditable(false);
        txtID.addActionListener(this::txtIDActionPerformed);

        jLabel6.setText("ID");

        txtTripID.addActionListener(this::txtTripIDActionPerformed);

        add.setText("Add");
        add.addActionListener(this::addActionPerformed);

        update.setText("Update");
        update.addActionListener(this::updateActionPerformed);

        Delete.setText("Delete");
        Delete.addActionListener(this::DeleteActionPerformed);

        jLabel7.setText("Total Revenue");

        txtRevenue.addActionListener(this::txtRevenueActionPerformed);

        search.setText("Search");
        search.addActionListener(this::searchActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtID)
                                    .addComponent(txtDep)
                                    .addComponent(txtRet)
                                    .addComponent(txtDestCount)
                                    .addComponent(txtPartCount)
                                    .addComponent(txtTripID, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(48, 48, 48)
                        .addComponent(add)
                        .addGap(50, 50, 50)
                        .addComponent(update)
                        .addGap(53, 53, 53)
                        .addComponent(Delete)
                        .addGap(47, 47, 47)
                        .addComponent(search)
                        .addGap(0, 44, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTripID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDestCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPartCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(update)
                    .addComponent(Delete)
                    .addComponent(jLabel7)
                    .addComponent(txtRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepActionPerformed

    private void txtRetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRetActionPerformed

    private void txtDestCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestCountActionPerformed

    private void txtPartCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPartCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPartCountActionPerformed

    private void txtTripIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTripIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTripIDActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         int row = jTable1.getSelectedRow();
        if (row != -1) {
            txtID.setText(jTable1.getValueAt(row, 0).toString());
            txtTripID.setText(jTable1.getValueAt(row, 1).toString());
            txtDep.setText(jTable1.getValueAt(row, 2).toString());
            txtRet.setText(jTable1.getValueAt(row, 3).toString());
            txtDestCount.setText(jTable1.getValueAt(row, 4).toString());
            txtPartCount.setText(jTable1.getValueAt(row, 5).toString());
            txtRevenue.setText(jTable1.getValueAt(row, 6).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        String id = txtID.getText(); 
        try (Connection con = DBConnection.connect(); 
             PreparedStatement pst = con.prepareStatement("DELETE FROM trip_history WHERE th_id = ?")) {
            pst.setInt(1, Integer.parseInt(id));
            pst.executeUpdate();
            loadHistoryData("SELECT * FROM trip_history ORDER BY th_departure DESC LIMIT 100");
            txtID.setText(""); txtTripID.setText("");
        } catch (Exception e) { JOptionPane.showMessageDialog(this, "Σφάλμα Delete: " + e.getMessage()); }
   
    }//GEN-LAST:event_DeleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String sql = "UPDATE trip_history SET th_trip_id=?, th_departure=?, th_return=?, th_destinations_count=?, th_participants_count=?, th_total_revenue=? WHERE th_id=?";
        try (Connection con = DBConnection.connect(); PreparedStatement pst = con.prepareStatement(sql)) {
        pst.setInt(1, Integer.parseInt(txtTripID.getText()));
        pst.setString(2, txtDep.getText());
        pst.setString(3, txtRet.getText());
        pst.setInt(4, Integer.parseInt(txtDestCount.getText()));
        pst.setInt(5, Integer.parseInt(txtPartCount.getText()));
        pst.setDouble(6, Double.parseDouble(txtRevenue.getText()));
        pst.setInt(7, Integer.parseInt(txtID.getText())); // Το κλειδί

        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Η εγγραφή ενημερώθηκε!");
        loadHistoryData("SELECT * FROM trip_history ORDER BY th_departure DESC LIMIT 100");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Σφάλμα Update: " + e.getMessage()); }
        
    }//GEN-LAST:event_updateActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        String sql = "INSERT INTO trip_history (th_trip_id, th_departure, th_return, th_destinations_count, th_participants_count, th_total_revenue) VALUES (?,?,?,?,?,?)";
        try (Connection con = DBConnection.connect(); PreparedStatement pst = con.prepareStatement(sql)) {
            pst.setInt(1, Integer.parseInt(txtTripID.getText()));
            pst.setString(2, txtDep.getText());
            pst.setString(3, txtRet.getText());
            pst.setInt(4, Integer.parseInt(txtDestCount.getText()));
            pst.setInt(5, Integer.parseInt(txtPartCount.getText()));
            pst.setDouble(6, Double.parseDouble(txtRevenue.getText()));

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record added to history!");
        } catch (Exception e) { JOptionPane.showMessageDialog(this, "Insert Error: " + e.getMessage()); }
    }//GEN-LAST:event_addActionPerformed

    private void txtRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRevenueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRevenueActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
       String tripId = txtTripID.getText().trim();
        String dateFrom = txtDep.getText().trim();

        String sql = "SELECT * FROM trip_history WHERE 1=1";
        if (!tripId.isEmpty()) sql += " AND th_trip_id = " + tripId;
        if (!dateFrom.isEmpty()) sql += " AND th_departure >= '" + dateFrom + " 00:00:00'";
        
        sql += " ORDER BY th_departure DESC LIMIT 1000";
        loadHistoryData(sql);
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TripHistoryForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton add;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton search;
    private javax.swing.JTextField txtDep;
    private javax.swing.JTextField txtDestCount;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtPartCount;
    private javax.swing.JTextField txtRet;
    private javax.swing.JTextField txtRevenue;
    private javax.swing.JTextField txtTripID;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
